name: CI

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Shellcheck
        run: shellcheck bin/*

  plugin-test-macos:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install mise
        run: |
          curl https://mise.run | sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH
      - name: Test plugin
        env:
          GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mise plugin install swiftlint $GITHUB_WORKSPACE
          mise install swiftlint@latest
          mise exec swiftlint -- swiftlint version

  plugin-test-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install mise
        run: |
          curl https://mise.run | sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH
      - name: Test plugin
        env:
          GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mise plugin install swiftlint $GITHUB_WORKSPACE
          mise install swiftlint@latest
          mise exec swiftlint -- swiftlint version
